# Generated by Django 4.2.2 on 2023-07-28 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeePersonalProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=250)),
                ('lastName', models.CharField(max_length=250)),
                ('dateBirth', models.DateField()),
                ('empEmail', models.CharField(max_length=250)),
                ('contactNo', models.BigIntegerField()),
                ('gender', models.CharField(max_length=20)),
                ('permanentAddress', models.CharField(max_length=250)),
                ('localAddress', models.CharField(max_length=250)),
                ('empPhoto', models.ImageField(upload_to='employee/')),
                ('fatherName', models.CharField(max_length=250)),
                ('motherName', models.CharField(max_length=250)),
                ('homeContact', models.BigIntegerField()),
                ('martialStatus', models.CharField(max_length=20)),
                ('spouseName', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeCompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountHolderName', models.CharField(max_length=250)),
                ('accountNumber', models.BigIntegerField()),
                ('bankName', models.CharField(max_length=250)),
                ('branch', models.CharField(max_length=250)),
                ('reportingManger', models.CharField(max_length=250)),
                ('dateJoining', models.DateField()),
                ('basicSalary', models.BigIntegerField()),
                ('employeeID', models.CharField(max_length=250)),
                ('Password', models.CharField(max_length=250)),
                ('department_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employer.department')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employer.employeepersonalprofile')),
                ('position_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employer.position')),
            ],
        ),
    ]
